# Generated by Django 4.1.6 on 2023-02-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0003_comments_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='isLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('liked', models.BooleanField()),
            ],
        ),
    ]
