# Generated by Django 4.1.6 on 2023-02-11 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.CharField(blank=True, max_length=100, null=True)),
                ('urlToImage', models.CharField(blank=True, max_length=500, null=True)),
                ('publishedAt', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=5000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='schemes',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='schemes',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
