# Generated by Django 4.1.6 on 2023-02-11 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0004_isliked'),
    ]

    operations = [
        migrations.AddField(
            model_name='isliked',
            name='post_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
