# Generated by Django 4.1.6 on 2023-02-11 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0005_isliked_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.AddField(
            model_name='feed',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Platform.comments'),
        ),
    ]
