# Generated by Django 4.1.6 on 2023-02-11 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Platform', '0006_remove_feed_comments_feed_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='comments',
        ),
        migrations.AddField(
            model_name='feed',
            name='comments',
            field=models.ManyToManyField(blank=True, null=True, to='Platform.comments'),
        ),
    ]
